# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GehzeitberechnungDialog
                                 A QGIS plugin
 This plugin calculates the walking time
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Flaminia Anselmi
        email                : flaminia.anselmi@vorarlberg.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets, QtCore
# from qgis.PyQt.QtWidgets import QDialog, QPushButton

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gehzeitberechnung_dialog_base.ui'))

class GehzeitberechnungDialog(QtWidgets.QDialog, FORM_CLASS):
    calculate_selected_clicked = QtCore.pyqtSignal()
    calculate_all_clicked = QtCore.pyqtSignal()
    
    def __init__(self, parent=None):
        """Constructor."""
        super(GehzeitberechnungDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.pushButton_cancel.clicked.connect(self.reject)
        self.pushButton_calculate_selected.clicked.connect(self.on_calculate_selected_clicked)
        self.pushButton_calculate_all.clicked.connect(self.on_calculate_all_clicked)

        self.pushButton_calculate_all.setEnabled(False) # button disabled by default

        self.checkBox_nur_nicht_Grenzkataster.stateChanged.connect(self.on_checkbox_state_changed)  # enable/disable based on checkbox

        self.groupBox_field_mapping.setVisible(False)   # hide field mapping container by default

        self.checkBox_update_table.stateChanged.connect(self.toggle_mapping_visibility)

    def on_calculate_selected_clicked(self):
        """Emit custom signal when 'Berechnen' is clicked."""
        
        self.calculate_selected_clicked.emit()

    def on_calculate_all_clicked(self):
        """Emit signal for 'Alles berechnen' button."""
        self.calculate_all_clicked.emit()

    def on_checkbox_state_changed(self, state):
        """Enable/disable the 'Alles berechnen' button."""
        is_checked = state == QtCore.Qt.Checked
        self.pushButton_calculate_all.setEnabled(is_checked)

    def toggle_mapping_visibility(self):
        """Show/hide field mapping controls based on checkbox."""
        active = self.checkBox_update_table.isChecked()
        self.groupBox_field_mapping.setVisible(active)

    def build_dynamic_mapping_ui(self, field_mapping, layer):
        """Dynamically build mapping UI rows based on self.field_mapping."""
        form = self.formLayout_field_mapping
        fields = layer.fields().names()

        # Clear previous dynamic widgets
        while form.rowCount() > 0:
            form.removeRow(0)

        self.mapping_dropdowns = {}

        for api_field in field_mapping.keys():
            label = QtWidgets.QLabel(api_field)
            combo = QtWidgets.QComboBox()

            combo.addItem("Kein Update")
            combo.addItems(fields)

            if api_field in fields:
                combo.setCurrentText(api_field)
            else:
                combo.setCurrentText("Kein Update")

            self.mapping_dropdowns[api_field] = combo

            form.addRow(label, combo)

    def get_selected_target_field(self, api_field):
        """Return the selected target field or None if 'Kein Update' is selected."""

        combo = self.mapping_dropdowns.get(api_field)
        if combo:
            text = combo.currentText()

            if text == "Kein Update":
                return None
            return text
        return None # if no combo is found