# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Gehzeitberechnung
                                 A QGIS plugin
 This plugin calculates the walking time
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Flaminia Anselmi
        email                : flaminia.anselmi@vorarlberg.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsProject, QgsField, QgsWkbTypes, QgsMessageLog, Qgis

# Initialize Qt resources from file resSources.py
from .resources import *
# Import the code for the dialog
from .gehzeitberechnung_dialog import GehzeitberechnungDialog
import os.path
from .api import fetch_hiking_data

QVARIANT_TO_STR = {
    QVariant.Invalid: "invalid",
    QVariant.Bool: "boolean",
    QVariant.Int: "integer",
    QVariant.LongLong: "integer",
    QVariant.Double: "double",
    QVariant.String: "string",
}

class Gehzeitberechnung:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        self.field_mapping = {
            "weg_laenge": {"path": "Zusammenfassung.Laenge 2D", "type": "double"},  
            "laenge_3d": {"path": "Zusammenfassung.Laenge 3D", "type": "double"},   
            "steig_max": {"path": "Zusammenfassung.Maximale Steigung", "type": "integer"},  
            "hm_auf_ri": {"path": "Zusammenfassung.Hoehenmeter Aufstieg", "type": "integer"},   
            "hm_auf_gri": {"path": "Zusammenfassung.Hoehenmeter Abstieg", "type": "integer"},   
            "ber_gz_ri": {"path": "Gehzeiten (min).Gehzeit gesamt hin", "type": "integer"},  
            "ber_gz_geg": {"path": "Gehzeiten (min).Gehzeit gesamt zurueck", "type": "integer"},  
        }
        
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Gehzeitberechnung_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.dlg = GehzeitberechnungDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Gehzeitberechnung')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Gehzeitberechnung', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/gehzeitberechnung/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Gehzeitberechnung'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Gehzeitberechnung'),
                action)
            self.iface.removeToolBarIcon(action)

    def log(self, text):
        """Log message to QGIS message log."""
        QgsMessageLog.logMessage(text, "Gehzeitberechnung", Qgis.Info)

    def validate_field_mapping(self, api_field, combo):
        """Validate the selected target field for the given api_field."""
        selected = combo.currentText()

        if selected == "Kein Update":   # always valid
            return
        
        layer = self.iface.activeLayer()
        if not layer:
            return

        required_type = self.field_mapping[api_field]["type"]

        idx = layer.fields().indexOf(selected)
        qgs_field = layer.fields().field(idx)
        actual_type = qgs_field.type()

        actual_type_str = QVARIANT_TO_STR.get(actual_type, f"Unbekannt ({actual_type})")

        if actual_type == QVariant.Double:
            target_type = "double"
        elif actual_type in (QVariant.Int, QVariant.LongLong):
            target_type = "integer"
        else:
            QMessageBox.warning(
                None,
                "Ungültiger Typ",
                f"Das Zielfeld {selected} ist vom Typ {actual_type_str}, "
                "hier kann kein Wert aus der API gespeichert werden."

            )
            combo.setCurrentText("Kein Update")
            return

        compatible = (
            (required_type == "integer" and target_type in ("integer", "double")) or
            (required_type == "double" and target_type == "double")
        )

        if not compatible:
            QMessageBox.warning(
                None,
                "Ungültige Feldzuordnung",
                (
                    f"Das Zielfeld {selected} ist vom Typ {actual_type_str}, "
                    f"aber {api_field} benötigt {required_type}.\n\n"
                    "Dies würde zu Datenverlust führen. Die Auswahl wurde zurückgesetzt."
                )
            )
            combo.setCurrentText("Kein Update")

    def get_nested_value(self, d, keys):
        """Get nested value from dict d using list of keys."""
        for key in keys:
            if isinstance(d, dict):
                d = d.get(key, None)
            else:
                return None
        return d
    
    def calculate_features(self, only_selected=True):
        """Perform the hiking time calculation for selected or all features."""

        url = "https://voibos.rechenraum.com/voibos/voibos"
        method = "viia"
        crs = "31254"

        layer = self.iface.activeLayer()
        if not layer or layer.geometryType() != QgsWkbTypes.LineGeometry:
            QMessageBox.warning(None, "Fehler", "Bitte eine Linien-Layer auswählen.")
            return

        if only_selected:
            features = layer.selectedFeatures()
            if not features:
                QMessageBox.warning(None, "Hinweis", "Keine ausgewählten Objekte gefunden.")
                return
        else:
            features = list(layer.getFeatures())

        update_activated = self.dlg.checkBox_update_table.isChecked()

        layer.startEditing()

        for feature in features:
            fid = feature.id()
            self.log("=" * 60)
            self.log(f"Feature ID: {fid}")
            self.log("-" * 60)

            before_values = {field: feature[field] for field in self.field_mapping.keys() if field in feature.fields().names()}
            self.log("Werte in der Attributtabelle VOR der Berechnung")

            for k, v in before_values.items():
                self.log(f"  • {k}: {v}")

            self.log("-" * 60)
            self.log("Werte von der API:")

            geom = feature.geometry()
            geom.transform(QgsCoordinateTransform(layer.crs(), QgsCoordinateReferenceSystem(crs), QgsProject.instance()))
            wkt = geom.asWkt()

            result = fetch_hiking_data(wkt, crs, method, url)
            if not result:
                print(f"Feature {fid}: API call failed")
                continue

            for field_name, field_info in self.field_mapping.items():
                value = self.get_nested_value(result, field_info["path"].split('.'))

                if value is not None:
                    if field_info["type"] == "double":
                        value = float(value)
                    elif field_info["type"] == "integer":
                        value = int(value)
                    else:
                        print(f"Unknown field type {field_info['type']} for field {field_name}")
                        continue

                self.log(f"  • {field_name}: {value}")

                if update_activated:
                    target_field = self.dlg.get_selected_target_field(field_name)

                    if target_field and target_field in feature.fields().names():
                        feature[target_field] = value

            if update_activated:
                layer.updateFeature(feature)

            after_values = {field: feature[field] for field in self.field_mapping.keys() if field in feature.fields().names()}
            self.log("-" * 60)
            self.log("Werte in der Attributtabelle NACH der Berechnung:")
            
            for k, v in after_values.items():
                self.log(f"  • {k}: {v}")

            self.log("=" * 60 + "\n")

        layer.commitChanges()

        QMessageBox.information(None, "Fertig", 
                                "Berechnung abgeschlossen.\n\n"
                                "Die Ergebnisse finden Sie im Protokollfenster unter:\n"
                                "Ansicht → Bedienfelder → Protokoll → Gehzeitberechnung")

    def run(self):
        """Run method that performs all the real work."""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started

        layer = self.iface.activeLayer()
        if not layer:
            QMessageBox.warning(None, "Fehler", "Bitte einen Layer auswählen.")
            return

        self.dlg.build_dynamic_mapping_ui(self.field_mapping, layer, self)

        # disconnect previous connections to avoid multiple triggers
        try:
            self.dlg.calculate_selected_clicked.disconnect()
        except Exception:
            pass
        try:
            self.dlg.calculate_all_clicked.disconnect()
        except Exception:
            pass

        self.dlg.calculate_selected_clicked.connect(lambda: (self.calculate_features(only_selected=True), self.dlg.accept()))
        self.dlg.calculate_all_clicked.connect(lambda: (self.calculate_features(only_selected=False), self.dlg.accept()))

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        # result = self.dlg.exec_()
        result = self.dlg.exec()
        # See if OK was pressed
        if not result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            return 
        