# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GehzeitberechnungDialog
                                 A QGIS plugin
 This plugin calculates the walking time
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Dietmar Palmetzhofer, Flaminia Anselmi
        email                : deitmar.palmetzhofer@vorarlberg.at, flaminia.anselmi@vorarlberg.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
# from qgis.PyQt.QtWidgets import QDialog, QPushButton

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gehzeitberechnung_dialog_base.ui'))


class GehzeitberechnungDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GehzeitberechnungDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton_cancel.clicked.connect(self.reject)
        # self.ui.pushButton_calculate_selected.clicked.connect(self.calculate_selected)
        # self.ui.pushButton_calculate_all.clicked.connect(self.calculate_all)

